### PR TITLE
.coafile: SpaceConsistencyBear parameter to true

### PR DESCRIPTION
**Pull request by RohanVB**
Corresponding to the `settings` in: https://github.com/coala/bear-docs/blob/master/docs/SpaceConsistencyBear.rst

### CODE REVIEW

**Comment by Udayan12167** [comment]
Hey while you are at it let's add CI as well so that this .coafile is used?

**Comment by RohanVB** [comment]
We might be deprecating coala-vim for syntastic/neomake, just waiting for some input on that.
I'll do this too asap since that might take some time.

> Hey while you are at it let's add CI as well so that this .coafile is used?

Will work on this along with proper tests :)

**Comment by supergr35** [comment]
ack eb4617a

**Comment by adtac** [comment]
ack https://github.com/coala/coala-vim/pull/30/commits/eb4617a36aefd8bbb6a64987f31f8dee85079dc1

**Comment by adtac** [comment]
@rultor merge

**Pull request merged**
